export const BAG_PRODUCT_REQUEST = "BAG_PRODUCT_REQUEST";
export const BAG_PRODUCT_SUCCESS = "BAG_PRODUCT_SUCCESS";
export const BAG_PRODUCT_FAIL = "BAG_PRODUCT_FAIL";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const NEWBAG_PRODUCT_REQUEST = "NEWBAG_PRODUCT_REQUEST";
export const NEWBAG_PRODUCT_SUCCESS = "NEWBAG_PRODUCT_SUCCESS";
export const NEWBAG_PRODUCT_RESET = "NEWBAG_PRODUCT_RESET";
export const NEWBAG_PRODUCT_FAIL = "NEWBAG_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const BAG_DETAILS_REQUEST = "BAG_DETAILS_REQUEST";
export const BAG_DETAILS_SUCCESS = "BAG_DETAILS_SUCCESS";
export const BAG_DETAILS_FAIL = "BAG_DETAILS_FAIL";

export const NEWBAG_REVIEW_REQUEST = "NEWBAG_REVIEW_REQUEST";
export const NEWBAG_REVIEW_SUCCESS = "NEWBAG_REVIEW_SUCCESS";
export const NEWBAG_REVIEW_RESET = "NEWBAG_REVIEW_RESET";
export const NEWBAG_REVIEW_FAIL = "NEWBAG_REVIEW_FAIL";

export const ALLBAG_REVIEW_REQUEST = "ALLBAG_REVIEW_REQUEST";
export const ALLBAG_REVIEW_SUCCESS = "ALLBAG_REVIEW_SUCCESS";
export const ALLBAG_REVIEW_FAIL = "ALLBAG_REVIEW_FAIL";

export const DELETEBAG_REVIEW_REQUEST = "DELETEBAG_REVIEW_REQUEST";
export const DELETEBAG_REVIEW_SUCCESS = "DELETEBAG_REVIEW_SUCCESS";
export const DELETEBAG_REVIEW_RESET = "DELETEBAG_REVIEW_RESET";
export const DELETEBAG_REVIEW_FAIL = "DELETBAG_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
