export const KID_PRODUCT_REQUEST = "KID_PRODUCT_REQUEST";
export const KID_PRODUCT_SUCCESS = "KID_PRODUCT_SUCCESS";
export const KID_PRODUCT_FAIL = "KID_PRODUCT_FAIL";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const NEWKID_PRODUCT_REQUEST = "NEWKID_PRODUCT_REQUEST";
export const NEWKID_PRODUCT_SUCCESS = "NEWKID_PRODUCT_SUCCESS";
export const NEWKID_PRODUCT_RESET = "NEWKID_PRODUCT_RESET";
export const NEWKID_PRODUCT_FAIL = "NEWKID_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const KID_DETAILS_REQUEST = "KID_DETAILS_REQUEST";
export const KID_DETAILS_SUCCESS = "KID_DETAILS_SUCCESS";
export const KID_DETAILS_FAIL = "KID_DETAILS_FAIL";

export const NEWKID_REVIEW_REQUEST = "NEWKID_REVIEW_REQUEST";
export const NEWKID_REVIEW_SUCCESS = "NEWKID_REVIEW_SUCCESS";
export const NEWKID_REVIEW_RESET = "NEWKID_REVIEW_RESET";
export const NEWKID_REVIEW_FAIL = "NEWKID_REVIEW_FAIL";

export const ALLKID_REVIEW_REQUEST = "ALLKID_REVIEW_REQUEST";
export const ALLKID_REVIEW_SUCCESS = "ALLKID_REVIEW_SUCCESS";
export const ALLKID_REVIEW_FAIL = "ALLKID_REVIEW_FAIL";

export const DELETEKID_REVIEW_REQUEST = "DELETEKID_REVIEW_REQUEST";
export const DELETEKID_REVIEW_SUCCESS = "DELETEKID_REVIEW_SUCCESS";
export const DELETEKID_REVIEW_RESET = "DELETEKID_REVIEW_RESET";
export const DELETEKID_REVIEW_FAIL = "DELETKID_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
