export const LATEST_PRODUCT_REQUEST = "LATEST_PRODUCT_REQUEST";
export const LATEST_PRODUCT_SUCCESS = "LATEST_PRODUCT_SUCCESS";
export const LATEST_PRODUCT_FAIL = "LATEST_PRODUCT_FAIL";

export const LATESTADMIN_PRODUCT_REQUEST = "LATESTADMIN_PRODUCT_REQUEST";
export const LATESTADMIN_PRODUCT_SUCCESS = "LATESTADMIN_PRODUCT_SUCCESS";
export const LATESTADMIN_PRODUCT_FAIL = "LATESTADMIN_PRODUCT_FAIL";

export const NEWLATEST_PRODUCT_REQUEST = "NEWLATEST_PRODUCT_REQUEST";
export const NEWLATEST_PRODUCT_SUCCESS = "NEWLATEST_PRODUCT_SUCCESS";
export const NEWLATEST_PRODUCT_RESET = "NEWLATEST_PRODUCT_RESET";
export const NEWLATEST_PRODUCT_FAIL = "NEWLATEST_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const LATESTPRODUCT_DETAILS_REQUEST = "LATESTPRODUCT_DETAILS_REQUEST";
export const LATESTPRODUCT_DETAILS_SUCCESS = "LATESTPRODUCT_DETAILS_SUCCESS";
export const LATESTPRODUCT_DETAILS_FAIL = "LATESTPRODUCT_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
