export const MOBILE_PRODUCT_REQUEST = "MOBILE_PRODUCT_REQUEST";
export const MOBILE_PRODUCT_SUCCESS = "MOBILE_PRODUCT_SUCCESS";
export const MOBILE_PRODUCT_FAIL = "MOBILE_PRODUCT_FAIL";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const NEWMOBILE_PRODUCT_REQUEST = "NEWMOBILE_PRODUCT_REQUEST";
export const NEWMOBILE_PRODUCT_SUCCESS = "NEWMOBILE_PRODUCT_SUCCESS";
export const NEWMOBILE_PRODUCT_RESET = "NEWMOBILE_PRODUCT_RESET";
export const NEWMOBILE_PRODUCT_FAIL = "NEWMOBILE_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const MOBILE_DETAILS_REQUEST = "MOBILE_DETAILS_REQUEST";
export const MOBILE_DETAILS_SUCCESS = "MOBILE_DETAILS_SUCCESS";
export const MOBILE_DETAILS_FAIL = "MOBILE_DETAILS_FAIL";

export const NEWMOBILE_REVIEW_REQUEST = "NEWMOBILE_REVIEW_REQUEST";
export const NEWMOBILE_REVIEW_SUCCESS = "NEWMOBILE_REVIEW_SUCCESS";
export const NEWMOBILE_REVIEW_RESET = "NEWMOBILE_REVIEW_RESET";
export const NEWMOBILE_REVIEW_FAIL = "NEWMOBILE_REVIEW_FAIL";

export const ALLMOBILE_REVIEW_REQUEST = "ALLMOBILE_REVIEW_REQUEST";
export const ALLMOBILE_REVIEW_SUCCESS = "ALLMOBILE_REVIEW_SUCCESS";
export const ALLMOBILE_REVIEW_FAIL = "ALLMOBILE_REVIEW_FAIL";

export const DELETEMOBILE_REVIEW_REQUEST = "DELETMOBILE_REVIEW_REQUEST";
export const DELETEMOBILE_REVIEW_SUCCESS = "DELETMOBILE_REVIEW_SUCCESS";
export const DELETEMOBILE_REVIEW_RESET = "DELETMOBILE_REVIEW_RESET";
export const DELETEMOBILE_REVIEW_FAIL = "DELETMOBILE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
