export const WOMEN_PRODUCT_REQUEST = "WOMEN_PRODUCT_REQUEST";
export const WOMEN_PRODUCT_SUCCESS = "WOMEN_PRODUCT_SUCCESS";
export const WOMEN_PRODUCT_FAIL = "WOMEN_PRODUCT_FAIL";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const WOMEN_DETAILS_REQUEST = "WOMEN_DETAILS_REQUEST";
export const WOMEN_DETAILS_SUCCESS = "WOMEN_DETAILS_SUCCESS";
export const WOMEN_DETAILS_FAIL = "WOMEN_DETAILS_FAIL";

export const NEWWOMEN_REVIEW_REQUEST = "NEWWOMEN_REVIEW_REQUEST";
export const NEWWOMEN_REVIEW_SUCCESS = "NEWWOMEN_REVIEW_SUCCESS";
export const NEWWOMEN_REVIEW_RESET = "NEWWOMEN_REVIEW_RESET";
export const NEWWOMEN_REVIEW_FAIL = "NEWWOMEN_REVIEW_FAIL";

export const ALLWOMEN_REVIEW_REQUEST = "ALLWOMEN_REVIEW_REQUEST";
export const ALLWOMEN_REVIEW_SUCCESS = "ALLWOMEN_REVIEW_SUCCESS";
export const ALLWOMEN_REVIEW_FAIL = "ALLWOMEN_REVIEW_FAIL";

export const DELETEWOMEN_REVIEW_REQUEST = "DELETEWOMEN_REVIEW_REQUEST";
export const DELETEWOMEN_REVIEW_SUCCESS = "DELETEWOMEN_REVIEW_SUCCESS";
export const DELETEWOMEN_REVIEW_RESET = "DELETEWOMEN_REVIEW_RESET";
export const DELETEWOMEN_REVIEW_FAIL = "DELETEWOMEN_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
